name: Build Docker Image

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
        
      - name: Check Gitlab CE latest version
        id: get_version
        run: |
          echo "PACKAGECLOUD_REPO=gitlab-ce" > ./RELEASE
          echo "RELEASE_PACKAGE=gitlab-ce" >> ./RELEASE
          echo "RELEASE_VERSION=${{ steps.vars.outputs.tag }}-ce.0" >> ./RELEASE
          echo "DOWNLOAD_URL=https://packages.gitlab.com/gitlab/gitlab-ce/packages/ubuntu/focal/gitlab-ce_${{ steps.vars.outputs.tag }}-ce.0_arm64.deb/download.deb" >> ./RELEASE
          echo "::set-output name=version::${{ steps.vars.outputs.tag }}"
          
      - name: Build and push
        uses: docker/build-push-action@v2
        if: steps.get_version.outputs.version != ''
        with:
          file: ./Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_NS }}/gitlab-ce-arm64:${{ steps.get_version.outputs.version }}-ce.0
            ${{ secrets.DOCKER_NS }}/gitlab-ce-arm64:latest
